services:
  view-available-room-service:
    build:
      context: ./services/view-available-room
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./services/view-available-room:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  booking-room-service:
    build:
      context: ./services/booking-room
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - ./services/booking-room:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  room-management-service:
    build:
      context: ./services/room-management
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    volumes:
      - ./services/room-management:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: telu-room-hub-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: telu_room_hub_eai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: telu-room-hub-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - db

volumes:
  mysql_data: